#-------------------------------

# General Site Settings



menu:

- {name: 'Home', url: ''}

# - {name: 'About', url: 'about'}

# - {name: 'Contact', url: 'contact'}



#-------------------------------

# SEO Section



# NOTE: Providing SEO information will make this website more searchable on the internet.



seo:

  description: 'Personal portfolio powered by Jekyll and GitHub Pages '

  rel-author: 'https://plus.google.com/u/0/#'

  rel-publisher: 'https://plus.google.com/u/0/#'



#-------------------------------

# Google Analytics Section



# Analytics helps you understand who visits your website.

# Learn more at: http://support.google.com/analytics/answer/1008065



# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.



google-analytics-ua: 'UA-127224975-1'


#-------------------------------

# Disqus Section



# Change to true for Disqus comments

disqus:

  comments: false

  disqus_shortname: 'thathungrymind'



#-------------------------------

# About Section



about: >

  # Portfolio Jekyll Theme




contact: >

  # Contact



#-------------------------------

# Work Section


#------------------------------

# Social 

social:
- {icon: 'behance', link: 'https://www.behance.net/pcabrera83', class: 'social-item-behance', iclass: 'hc-behance'}
- {icon: 'github', link: 'https://github.com/pcabrera83', class: 'social-item-github', iclass: 'hc-github'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/patricio-cabrera-2349a028/', class: 'social-item-linkedin', iclass: 'hc-linkedin'}
- {icon: 'twitter', link: 'https://twitter.com/patricio6883', class: 'social-item-twitter' , iclass: 'hc-twitter'}